"""List of holidays in Chile, got from https://apis.digital.gob.cl/fl/ .
Holidays previous to 2013 where added manually, from www.feriadoschilenos.cl/ .
"""
# Some holidays that are not in the list and may be added:
# - 2013-06-30: elecciones primarias (presidenciales y congresistas)
#               (irrenunciable de segunda categoría)
HOLIDAYS = [
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2011-01-01',
     'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2011-04-22',
     'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'S\u00e1bado Santo', 'comentarios': '', 'fecha': '2011-04-23',
     'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2011-05-01', 'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2011-05-21', 'irrenunciable': '0', 'tipo': 'Civil'},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2011-06-27', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2011-07-16', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2011-08-15', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2011-09-18', 'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2011-09-19', 'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2011-10-10', 'irrenunciable': '0', 'tipo': 'Civil'},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2011-10-31', 'irrenunciable': '0',
     'tipo': 'Religioso', },
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': '',
     'fecha': '2011-11-01', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': '',
     'fecha': '2011-12-08', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'Navidad', 'comentarios': '', 'fecha': '2011-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso'},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2012-01-01',
     'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2012-04-06',
     'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'S\u00e1bado Santo', 'comentarios': '', 'fecha': '2012-04-07',
     'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2012-05-01', 'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2012-05-21', 'irrenunciable': '0', 'tipo': 'Civil'},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2012-07-02', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2012-07-16', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2012-08-15', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'Fiestas Patrias', 'comentarios': '', 'fecha': '2012-09-17',
     'irrenunciable': '0', 'tipo': 'Civil'},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2012-09-18', 'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2012-09-19', 'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2012-10-15', 'irrenunciable': '0', 'tipo': 'Civil'},
    {'nombre': 'Elecciones Municipales', 'comentarios': '',
     'fecha': '2012-10-28', 'irrenunciable': '0', 'tipo': 'Civil'},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': '',
     'fecha': '2012-11-01', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2012-11-02', 'irrenunciable': '0',
     'tipo': 'Religioso'},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': '',
     'fecha': '2012-12-08', 'irrenunciable': '0', 'tipo': 'Religioso'},
    {'nombre': 'Navidad', 'comentarios': '', 'fecha': '2012-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso'},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2013-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 20.215',
                'url': 'http://www.leychile.cl/Navegar?idNorma=264651'},
               {'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': '',
     'fecha': '2013-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2013-03-29',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'S\u00e1bado Santo', 'comentarios': '', 'fecha': '2013-03-30',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2013-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'},
               {'nombre': 'C\u00f3digo del Trabajo',
                'url': 'http://www.leychile.cl/Navegar?idNorma=207436'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2013-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2013-06-29', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2013-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2013-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2013-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2013-09-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Fiestas Patrias', 'comentarios': '', 'fecha': '2013-09-20',
     'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 20.215',
                'url': 'http://www.leychile.cl/Navegar?idNorma=264651'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2013-10-12', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'},
               {'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'}]},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2013-10-31', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': '',
     'fecha': '2013-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Elecciones Presidenciales y Parlamentarias', 'comentarios': '',
     'fecha': '2013-11-17', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 18.700',
                'url': 'http://www.leychile.cl/Navegar?idNorma=30082'},
               {'nombre': 'Ley 20.354',
                'url': 'http://www.leychile.cl/Navegar?idLey=20354'},
               {'nombre': 'Ley 20.515',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1027335'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': '',
     'fecha': '2013-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Segunda Vuelta Elecciones Presidenciales',
     'comentarios': 'Depende del resultado de la primera vuelta',
     'fecha': '2013-12-15', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 18.700',
                'url': 'http://www.leychile.cl/Navegar?idNorma=30082'},
               {'nombre': 'Ley 20.354',
                'url': 'http://www.leychile.cl/Navegar?idLey=20354'},
               {'nombre': 'Ley 20.515',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1027335'}]},
    {'nombre': 'Navidad', 'comentarios': '', 'fecha': '2013-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2014-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': '',
     'fecha': '2014-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2014-04-18',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'S\u00e1bado Santo', 'comentarios': '', 'fecha': '2014-04-19',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2014-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'C\u00f3digo del Trabajo',
                'url': 'http://www.leychile.cl/Navegar?idNorma=207436'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2014-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2014-06-29', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2014-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2014-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2014-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2014-09-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2014-10-12', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2014-10-31', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': '',
     'fecha': '2014-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': '',
     'fecha': '2014-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Navidad', 'comentarios': '', 'fecha': '2014-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': '',
     'fecha': '2015-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2015-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2015-04-03',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'S\u00e1bado Santo', 'comentarios': '', 'fecha': '2015-04-04',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2015-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'C\u00f3digo del Trabajo',
                'url': 'http://www.leychile.cl/Navegar?idNorma=207436'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2015-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2015-06-29', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2015-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2015-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2015-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2015-09-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2015-10-12', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2015-10-31', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': '',
     'fecha': '2015-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': '',
     'fecha': '2015-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Navidad', 'comentarios': '', 'fecha': '2015-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2016-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': '',
     'fecha': '2016-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2016-03-25',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'S\u00e1bado Santo', 'comentarios': '', 'fecha': '2016-03-26',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2016-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2016-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Elecciones Primarias Municipales - sujeto a modificaci\u00f3n',
     'comentarios': '', 'fecha': '2016-06-12', 'irrenunciable': '1',
     'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'},
               {'nombre': 'Ley 20.640',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1046533'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2016-06-27', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2016-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2016-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2016-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2016-09-19', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2016-10-10', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'Elecciones Municipales',
     'comentarios': ('Este feriado en primera instancia era para el 30 '
                     'del mismo mes, pero se decidi\u00f3 cambiar la fecha '
                     'de los comicios debido a que ca\u00eda en fin de semana '
                     'largo y podr\u00eda generar abstenci\u00f3n.  '
                     'Leyes: Ley de Municipalidades'),
     'fecha': '2016-10-23', 'irrenunciable': '1', 'tipo': 'Civil'},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2016-10-31', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'D\u00eda de todos los Santos', 'comentarios': '',
     'fecha': '2016-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': '',
     'fecha': '2016-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Navidad', 'comentarios': '', 'fecha': '2016-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': '',
     'fecha': '2017-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2017-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': 'Feriado Adicional',
     'fecha': '2017-01-02', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 20.983',
                'url': 'https://www.leychile.cl/Navegar?idNorma=1098384'}]},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2017-04-14',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Sabado Santo', 'comentarios': '', 'fecha': '2017-04-15',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Censo Nacional Abreviado', 'comentarios': '',
     'fecha': '2017-04-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 19.790',
                'url': 'https://www.leychile.cl/Navegar?idNorma=194251'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2017-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'C\u00f3digo del Trabajo',
                'url': 'http://www.leychile.cl/Navegar?idNorma=207436'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2017-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2017-06-26', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'Elecciones Primarias',
     'comentarios': ('Se debe confirmar la realizaci\u00f3n de la '
                     'Elecci\u00f3n Primaria.'),
     'fecha': '2017-07-02', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 20.640',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1046533'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2017-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2017-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2017-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2017-09-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2017-10-09', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2017-10-27', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': '',
     'fecha': '2017-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Elecci\u00f3n Presidencial y Parlamentaria', 'comentarios': '',
     'fecha': '2017-11-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 18.700',
                'url': 'http://www.leychile.cl/Navegar?idNorma=30082'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': '',
     'fecha': '2017-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Segunda Vuelta Elecci\u00f3n Presidencial',
     'comentarios': ('Se debe confirmar la realizaci\u00f3n de la '
                     'Segunda Vuelta.'),
     'fecha': '2017-12-17', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 18.700',
                'url': 'http://www.leychile.cl/Navegar?idNorma=30082'}]},
    {'nombre': 'Navidad', 'comentarios': '', 'fecha': '2017-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': '',
     'fecha': '2018-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': '', 'fecha': '2018-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Visita de Su Santidad el Papa Francisco', 'comentarios': '',
     'fecha': '2018-01-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 21.065',
                'url': 'https://www.leychile.cl/Navegar?idNorma=1113434'}]},
    {'nombre': 'Viernes Santo', 'comentarios': '', 'fecha': '2018-03-30',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Sabado Santo', 'comentarios': '', 'fecha': '2018-03-31',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': '',
     'fecha': '2018-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'C\u00f3digo del Trabajo',
                'url': 'http://www.leychile.cl/Navegar?idNorma=207436'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': '',
     'fecha': '2018-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': '',
     'fecha': '2018-07-02', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': '',
     'fecha': '2018-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': '',
     'fecha': '2018-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Fiestas Patrias\t', 'comentarios': '', 'fecha': '2018-09-17',
     'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 20.215',
                'url': 'http://www.leychile.cl/Navegar?idNorma=264651'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': '',
     'fecha': '2018-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': '',
     'fecha': '2018-09-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': '',
     'fecha': '2018-10-15', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': '',
     'fecha': '2018-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': '', 'fecha': '2018-11-02', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': ' ',
     'fecha': '2018-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Navidad', 'comentarios': ' ', 'fecha': '2018-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': ' ',
     'fecha': '2019-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': ' ', 'fecha': '2019-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Viernes Santo', 'comentarios': ' ', 'fecha': '2019-04-19',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'S\u00e1bado Santo', 'comentarios': ' ', 'fecha': '2019-04-20',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': ' ',
     'fecha': '2019-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'C\u00f3digo del Trabajo',
                'url': 'http://www.leychile.cl/Navegar?idNorma=207436'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': ' ',
     'fecha': '2019-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': ' ',
     'fecha': '2019-06-29', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': ' ',
     'fecha': '2019-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': ' ',
     'fecha': '2019-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': ' ',
     'fecha': '2019-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ej\u00e9rcito', 'comentarios': ' ',
     'fecha': '2019-09-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Fiestas Patrias', 'comentarios': ' ', 'fecha': '2019-09-20',
     'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 20.215',
                'url': 'http://www.leychile.cl/Navegar?idNorma=264651'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': ' ',
     'fecha': '2019-10-12', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': ' ', 'fecha': '2019-10-31', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': ' ',
     'fecha': '2019-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': ' ',
     'fecha': '2019-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Navidad', 'comentarios': ' ', 'fecha': '2019-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': ' ',
     'fecha': '2020-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': ' ', 'fecha': '2020-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'},
               {'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Viernes Santo', 'comentarios': ' ', 'fecha': '2020-04-10',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Sabado Santo', 'comentarios': ' ', 'fecha': '2020-04-11',
     'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Plebiscito Constitucional', 'comentarios': ' ',
     'fecha': '2020-04-26', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 21.200',
                'url': 'https://www.leychile.cl/Navegar?idNorma=1140340'},
               {'nombre': 'Ley 18.700',
                'url': 'http://www.leychile.cl/Navegar?idNorma=30082'}]},
    {'nombre': 'D\u00eda Nacional del Trabajo', 'comentarios': ' ',
     'fecha': '2020-05-01', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'C\u00f3digo del Trabajo',
                'url': 'http://www.leychile.cl/Navegar?idNorma=207436'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias Navales', 'comentarios': ' ',
     'fecha': '2020-05-21', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Elecciones Primarias de Alcalde', 'comentarios': ' ',
     'fecha': '2020-06-07', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 20.640',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1046533'},
               {'nombre': 'Ley 18.700',
                'url': 'http://www.leychile.cl/Navegar?idNorma=30082'}]},
    {'nombre': 'San Pedro y San Pablo', 'comentarios': ' ',
     'fecha': '2020-06-29', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 18.432',
                'url': 'http://www.leychile.cl/Navegar?idNorma=29840'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'D\u00eda de la Virgen del Carmen', 'comentarios': ' ',
     'fecha': '2020-07-16', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.148',
                'url': 'http://www.leychile.cl/Navegar?idNorma=257080'}]},
    {'nombre': 'Asunci\u00f3n de la Virgen', 'comentarios': ' ',
     'fecha': '2020-08-15', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Independencia Nacional', 'comentarios': ' ',
     'fecha': '2020-09-18', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'D\u00eda de las Glorias del Ejercito', 'comentarios': ' ',
     'fecha': '2020-09-19', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 20.629',
                'url': 'http://www.leychile.cl/Navegar?idNorma=1043726'}]},
    {'nombre': 'Encuentro de Dos Mundos', 'comentarios': ' ',
     'fecha': '2020-10-12', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 3.810',
                'url': 'http://www.leychile.cl/Navegar?idNorma=24262'},
               {'nombre': 'Ley 19.668',
                'url': 'http://www.leychile.cl/Navegar?idNorma=160270'}]},
    {'nombre': 'Elecciones Municipales', 'comentarios': ' ',
     'fecha': '2020-10-25', 'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 18.695',
                'url': 'https://www.leychile.cl/Navegar?idNorma=251693'},
               {'nombre': 'Ley 18.700',
                'url': 'http://www.leychile.cl/Navegar?idNorma=30082'}]},
    {'nombre': 'D\u00eda de las Iglesias Evang\u00e9licas y Protestantes',
     'comentarios': ' ', 'fecha': '2020-10-31', 'irrenunciable': '0',
     'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 20.299',
                'url': 'http://www.leychile.cl/Navegar?idNorma=279294'}]},
    {'nombre': 'D\u00eda de Todos los Santos', 'comentarios': ' ',
     'fecha': '2020-11-01', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Inmaculada Concepci\u00f3n', 'comentarios': ' ',
     'fecha': '2020-12-08', 'irrenunciable': '0', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'Navidad', 'comentarios': ' ', 'fecha': '2020-12-25',
     'irrenunciable': '1', 'tipo': 'Religioso',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]},
    {'nombre': 'Todos los D\u00edas Domingos', 'comentarios': ' ',
     'fecha': '2021-01-01', 'irrenunciable': '0', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'}]},
    {'nombre': 'A\u00f1o Nuevo', 'comentarios': ' ', 'fecha': '2021-01-01',
     'irrenunciable': '1', 'tipo': 'Civil',
     'leyes': [{'nombre': 'Ley 2.977',
                'url': 'http://www.leychile.cl/Navegar?idNorma=23639'},
               {'nombre': 'Ley 19.973',
                'url': 'http://www.leychile.cl/Navegar?idNorma=230132'}]}]
